Books/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Books.Models {

   public class Book {
      public int Id {
         get;
         set;
      }

      [Required]
      [DisplayName("Book Title")]
      public string Title {
         get;
         set;
      }

      [Required]
      [DisplayName("Last Name")]
      public string AuthorLastName {
         get;
         set;
      }

      [Required]
      [DisplayName("First Name")]
      public string AuthorFirstName {
         get;
         set;
      }

      public string Author {
         get {
            return String.Format("{0} {1}", AuthorFirstName, AuthorLastName);
         }
      }

      [RegularExpression(@"\d{4}", ErrorMessage="Year must be a 4 digit value.")]
      public int Year {
         get;
         set;
      }
   }
}

Books/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Books.Models;
using PagedList;

namespace Books.Controllers {
   [Authorize]
   public class BookController : Controller {

      private ApplicationDbContext db = new ApplicationDbContext();

      // GET: Book
      public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page) {

         ViewBag.CurrentSort = sortOrder;

         ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
         ViewBag.AuthorSortParm = sortOrder == "author" ? "author_desc" : "author";
         ViewBag.YearSortParm = sortOrder == "year" ? "year_desc" : "year";

         if (searchString != null) {
            page = 1;
         } else {
            searchString = currentFilter;
         }

         ViewBag.CurrentFilter = searchString;

         var books = from b in db.Books select b;
         if (!String.IsNullOrEmpty(searchString)) {
            books = books.Where(b => b.AuthorLastName.Contains(searchString)
                                   || b.AuthorFirstName.Contains(searchString));
         }

         switch (sortOrder) {
            case "author":
               books = books.OrderBy(b => b.AuthorLastName);
               break;
            case "author_desc":
               books = books.OrderByDescending(b => b.AuthorLastName);
               break;
            case "year":
               books = books.OrderBy(b => b.Year);
               break;
            case "year_desc":
               books = books.OrderByDescending(b => b.Year);
               break;
            case "title_desc":
               books = books.OrderByDescending(b => b.Title);
               break;
            default:
               books = books.OrderBy(b => b.Title);
               break;
         }

         int pageSize = 5;
         int pageNumber = (page ?? 1);
         return View(books.ToPagedList(pageNumber, pageSize));
      }

      // GET: Book/Details/5
      public ActionResult Details(int? id) {
         if (id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Book book = db.Books.Find(id);
         if (book == null) {
            return HttpNotFound();
         }
         return View(book);
      }

      // GET: Book/Create
      public ActionResult Create() {
         return View();
      }

      // POST: Book/Create
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create([Bind(Include = "Id,Title,AuthorLastName,AuthorFirstName,Year")] Book book) {
         if (ModelState.IsValid) {
            db.Books.Add(book);
            db.SaveChanges();
            return RedirectToAction("Index");
         }

         return View(book);
      }

      // GET: Book/Edit/5
      public ActionResult Edit(int? id) {
         if (id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Book book = db.Books.Find(id);
         if (book == null) {
            return HttpNotFound();
         }
         ViewData["Id"] = id;
         return View(book);
      }

      // POST: Book/Edit/5
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit([Bind(Include = "Id,Title,AuthorLastName,AuthorFirstName,Year")] Book book) {
         if (ModelState.IsValid) {
            db.Entry(book).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         return View(book);
      }

      // GET: Book/Delete/5
      public ActionResult Delete(int? id) {
         if (id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Book book = db.Books.Find(id);
         if (book == null) {
            return HttpNotFound();
         }
         return View(book);
      }

      // POST: Book/Delete/5
      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public ActionResult DeleteConfirmed(int id) {
         Book book = db.Books.Find(id);
         db.Books.Remove(book);
         db.SaveChanges();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing) {
         if (disposing) {
            db.Dispose();
         }
         base.Dispose(disposing);
      }
   }
}

Books/Views/Book/Create.cshtml
@model Books.Models.Book

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
               <input type="submit" value="Create" class="btn btn-default" />
               @Html.ActionLink("Cancel", "Index", "Book", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Books/Views/Book/Delete.cshtml
@model Books.Models.Book

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
           <input type="submit" value="Delete" class="btn btn-default" /> 
           @Html.ActionLink("Cancel", "Index", "Book", new {@class = "btn btn-default"})
        </div>
    }
</div>

Books/Views/Book/Details.cshtml
@model Books.Models.Book

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Books/Views/Book/Edit.cshtml
@model Books.Models.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
               <input type="submit" value="Save" class="btn btn-default" /> 
               @Html.ActionLink("Delete", "Delete", "Book", new {id = ViewData["Id"]}, new {@class = "btn btn-default"})
               @Html.ActionLink("Cancel", "Index", "Book", new {@class = "btn btn-default"})
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Books/Views/Book/Index.cshtml
@model PagedList.IPagedList<Books.Models.Book>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
   ViewBag.Title = "The Book List";
}

<h2>The Book List</h2>

<p>
   @Html.ActionLink("Add New Book", "Create")
</p>
@using (Html.BeginForm("Index", "Book", FormMethod.Get)) {
   <p>
      Find by Author: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
      <input type="submit" value="Search" />
   </p>
}
<table class="table table-striped table-bordered">
   <thead>
      <tr>
        <th> 
           @Html.ActionLink("Title", "Index", new {sortOrder = ViewBag.TitleSortParm, currentFilter = ViewBag.CurrentFilter})
        </th>
        <th>
           @Html.ActionLink("Author", "Index", new {sortOrder = ViewBag.AuthorSortParm, currentFilter = ViewBag.CurrentFilter})
        </th>
        <th>
           @Html.ActionLink("Year", "Index", new {sortOrder = ViewBag.YearSortParm, currentFilter = ViewBag.CurrentFilter})
        </th>
      </tr>
   </thead>

   <tbody>
      @foreach (var item in Model) {
         <tr>
            <td>@Html.DisplayFor(modelItem => item.Title)</td>
            <td>@Html.DisplayFor(modelItem => item.Author)</td>
            <td>@Html.DisplayFor(modelItem => item.Year)</td>
            <td>
               @Html.ActionLink("Edit", "Edit", new {id = item.Id})
             </td>
         </tr>
      }
   </tbody>   
</table>
<br />
      Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
      @Html.PagedListPager(Model, page => Url.Action("Index", new {
          page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter
       }))